/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as ProgramKerjaRouteImport } from './routes/program-kerja'
import { Route as EdukasiRouteImport } from './routes/edukasi'
import { Route as BerandaRouteImport } from './routes/beranda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EdukasiVideoRouteImport } from './routes/edukasi_.video'

const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramKerjaRoute = ProgramKerjaRouteImport.update({
  id: '/program-kerja',
  path: '/program-kerja',
  getParentRoute: () => rootRouteImport,
} as any)
const EdukasiRoute = EdukasiRouteImport.update({
  id: '/edukasi',
  path: '/edukasi',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRoute = BerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EdukasiVideoRoute = EdukasiVideoRouteImport.update({
  id: '/edukasi_/video',
  path: '/edukasi/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/edukasi': typeof EdukasiRoute
  '/program-kerja': typeof ProgramKerjaRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/edukasi/video': typeof EdukasiVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/edukasi': typeof EdukasiRoute
  '/program-kerja': typeof ProgramKerjaRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/edukasi/video': typeof EdukasiVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/edukasi': typeof EdukasiRoute
  '/program-kerja': typeof ProgramKerjaRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/edukasi_/video': typeof EdukasiVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beranda'
    | '/edukasi'
    | '/program-kerja'
    | '/tentang-kami'
    | '/edukasi/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beranda'
    | '/edukasi'
    | '/program-kerja'
    | '/tentang-kami'
    | '/edukasi/video'
  id:
    | '__root__'
    | '/'
    | '/beranda'
    | '/edukasi'
    | '/program-kerja'
    | '/tentang-kami'
    | '/edukasi_/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerandaRoute: typeof BerandaRoute
  EdukasiRoute: typeof EdukasiRoute
  ProgramKerjaRoute: typeof ProgramKerjaRoute
  TentangKamiRoute: typeof TentangKamiRoute
  EdukasiVideoRoute: typeof EdukasiVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-kerja': {
      id: '/program-kerja'
      path: '/program-kerja'
      fullPath: '/program-kerja'
      preLoaderRoute: typeof ProgramKerjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edukasi': {
      id: '/edukasi'
      path: '/edukasi'
      fullPath: '/edukasi'
      preLoaderRoute: typeof EdukasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edukasi_/video': {
      id: '/edukasi_/video'
      path: '/edukasi/video'
      fullPath: '/edukasi/video'
      preLoaderRoute: typeof EdukasiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerandaRoute: BerandaRoute,
  EdukasiRoute: EdukasiRoute,
  ProgramKerjaRoute: ProgramKerjaRoute,
  TentangKamiRoute: TentangKamiRoute,
  EdukasiVideoRoute: EdukasiVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
