/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as ProgramKerjaRouteImport } from './routes/program-kerja'
import { Route as EdukasiRouteImport } from './routes/edukasi'
import { Route as IndexRouteImport } from './routes/index'

const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramKerjaRoute = ProgramKerjaRouteImport.update({
  id: '/program-kerja',
  path: '/program-kerja',
  getParentRoute: () => rootRouteImport,
} as any)
const EdukasiRoute = EdukasiRouteImport.update({
  id: '/edukasi',
  path: '/edukasi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edukasi': typeof EdukasiRoute
  '/program-kerja': typeof ProgramKerjaRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edukasi': typeof EdukasiRoute
  '/program-kerja': typeof ProgramKerjaRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edukasi': typeof EdukasiRoute
  '/program-kerja': typeof ProgramKerjaRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/edukasi' | '/program-kerja' | '/tentang-kami'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/edukasi' | '/program-kerja' | '/tentang-kami'
  id: '__root__' | '/' | '/edukasi' | '/program-kerja' | '/tentang-kami'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EdukasiRoute: typeof EdukasiRoute
  ProgramKerjaRoute: typeof ProgramKerjaRoute
  TentangKamiRoute: typeof TentangKamiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-kerja': {
      id: '/program-kerja'
      path: '/program-kerja'
      fullPath: '/program-kerja'
      preLoaderRoute: typeof ProgramKerjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edukasi': {
      id: '/edukasi'
      path: '/edukasi'
      fullPath: '/edukasi'
      preLoaderRoute: typeof EdukasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EdukasiRoute: EdukasiRoute,
  ProgramKerjaRoute: ProgramKerjaRoute,
  TentangKamiRoute: TentangKamiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
